### ISSUE TITLE
Getting nasty error message all the time.

### ISSUE THREAD

**Issue by FrankenApps** [stephenkubovic/electron-music-player#1]
It looks like so:
![error_electron](https://cloud.githubusercontent.com/assets/17967303/15269012/1fde573e-19f2-11e6-8700-4510f63f88ce.png)
Is it because of my electron version? I have 0.37.8

**Comment by stephenkubovic** [comment]
Thanks for your interest in this.  I have not looked at this project in many months (almost a year!) since it was never meant as anything more than a way for me to start playing around with Electron.  I just pulled the code down again and tried running against Electron 1.1.0 and it does not even open.

If you are still interested in playing around with this, I'd more than happily accept a PR that makes it work on the latest Electron, but I don't think I'll be dedicating much time to developing this further, in as it was never intended to be a "real" project.

I will update the README to reflect the nature of this project.

**Comment by ssi-anik** [comment]
Replacing the following 
```
import app from 'app'
import BrowserWindow from 'browser-window'
import ipc from 'ipc'
import dialog from 'dialog'
```
with
```
import {app, BrowserWindow, ipcMain as ipc, dialog} from 'electron'
```
And, main.js#15
```
mainWindow.loadUrl(`file://${filepath}`)
```
with
```
mainWindow.loadURL(`file://${filepath}`)
```
removed the build/start issues. Nothing happens afterward.
